# 
# LAST UPDATE: 2021-06-04 15:25:00-5
#=================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: localhost #change to your hostname if running your own instance
        port: 5000
    url: http://localhost:5000 #change to host URL  if running your own instance
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 100
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net
    # templates:
    #  path: /skin-dashboard/templates
    #  static: /skin-dashboard/static

logging:
    level: ERROR
    logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Hydrosource Reference Features
        description: Provides linked data for hydrologic features across Hydrosource datasets
        keywords:
            - geospatial
            - data
            - api
            - hydropower
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/internetofwater/geoconnex.us
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Hydrosource
        url: https://hydrosource.ornl.gov
    contact:
        address: 
        city: 
        stateorprovince: 
        postalcode: 
        country: USA
        email: debd@ornl.gov
        url: https://hydrosource.ornl.gov
        role: pointOfContact

resources:
    dams:
        type: collection
        title: Dams
        description: Dams represented across Hydrosource datasets
        keywords:
            - Dams
        context:
            - schema: https://schema.org/
              dam_name: schema:name
              state_uri: 
                  "@id": schema:geoWithin
                  "@type": "@id"
              huc_uri: 
                  "@id": schema:geoWithin
                  "@type": "@id"
              id_eha: schema:identifier
              id_hilarri: schema:identifier
              id_fcdocket: schema:identifier
              id_nid: schema:identifier
              hyf_type:
                  "@id": http://www.opengeospatial.org/standards/waterml2/hy_features/HY_HydroLocationType
                  "@type": "@id"
              hyf:
                  "@id": "@type"
                  "@type": "@id"
              huc12_uri: schema:geoWithin
              comid_uri: http://www.opengeospatial.org/standards/waterml2/hy_features/flowpath
              HILARRI_2021:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
              EHA_Annual_Capacity:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
              EHA_Annual_CapacityFactor:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
              EHA_Annual_Gross_Generation:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
              ORNL_Retired_FY2020_revised:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
              ORNL_US_Hydropower_DevelopmentPipeline_Data_FY2021:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
              ORNL_CostofMitigatingEnvironmentalImpacts_FY2021:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
              ORNL_Mitigation_Database:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
              EHA_Annual_Net_Generation:
                   "@id": "schema:subjectOf"
                   "@type": "@id"
        links: 
            - type: application/html
              rel: canonical
              title: EPA PWSID List source
              href: https://hydrosource.ornl.gov
              hreflang: en-US
        extents:
            spatial:
                bbox: [-170,15,-51,72]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null
        providers:
            - type: feature
              name: GeoJSON
              data: /data/dams.geojson
              id_field: hydrosource_id
              uri_field: uri